### ISSUE TITLE
Set up kanban board

### ISSUE THREAD

**Issue by cynthiainga** [cynthiainga/JavaScript-groupe-capstone#21]
https://github.com/cynthiainga/JavaScript-groupe-capstone/projects/1

We are a group of two students: -Lynette and Cynthia

**Comment by cynthiainga** [comment]
Thanks, we have already assigned all the cards to specific members.

**Comment by Kingstalux** [comment]
Hi @cynthiainga and @iLynette ,
# Status: Approved ✔️ ✔️ ✔️ 
 
![128382030-38e7de91-f6f2-45cf-b54e-8068e0446e4c](https://user-images.githubusercontent.com/85113567/157077889-bf663517-1878-41be-b3c1-0502833ed686.gif)

Good job implementing the required changes 👍 Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
